### PR TITLE
Support Persistent 2.11 and improve error output.

### PR DESCRIPTION
**Pull request by friedbrice**

### CODE REVIEW

**Comment by MaxGabriel** [comment]
I tested this patch in our production codebase and can confirm it works

**Comment by MaxGabriel** [comment]
I updated https://hackage.haskell.org/package/persistent-iproute-0.2.4 to have persistent < 2.11.0.0 for its bounds

**Comment by greydot** [comment]
Thanks @MaxGabriel!
I'll merge this and upload the new version to hackage shortly.

**Comment by greydot** [comment]
The new version is out.

**Pull request merged**
